baseURL: "https://wangyida.github.io/"
title: Yida Wang
paginate: 8
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: ExampleSite
    description: "ExampleSite description"
    keywords: [Blog, Portfolio, PaperMod]
    author: Yida
    # author: ["Me", "You"] # multiple authors
    images: ["http://campar.in.tum.de/twiki/pub/Main/YidaWang/YidaWang_CAMP.png"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "/icon_Y.png"
        favicon16x16: "<link / abs url>"
        favicon32x32: "/icon_Y32x32.png"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "/icon_Y32x32.png"

    label:
        text: ". WANG"
        icon: /icon_Y.png
        iconHeight: 28

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: Yida Wang
        subtitle: "Ph.D. student focused on computer vision and machine learning"
        imageUrl: "Photo_race.jpg"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Yida WANG \U00002728"
        Content: >
          I'm a Ph.D. student focused on computer vision and machine learning from [Technische Universität München](https://www.tum.de/), with topic of deep learning techniques for representation and processing of 3D data for complex visual tasks. Ever enrolled in competer vision projects sponsored by Microsoft and Google, *e.g.* [tiny-dnn](https://github.com/tiny-dnn/tiny-dnn) and [3D pose estimation](https://github.com/opencv/opencv_contrib/tree/master/modules/cnn_3dobj). [Presentation](/Presentation_Yida.pdf)

          > - **Download**: [My Resume](/resume_yida_en.pdf), [中文简历](/resume_yida_cn.pdf) and [Lebenslauf](/resume_yida_de.pdf)

    socialIcons:
        - name: linkedin
          url: "https://www.linkedin.com/in/yida-wang-910123"
        - name: googlescholar
          url: "https://scholar.google.com/citations?user=HpfFgYIAAAAJ&hl=en"
        - name: github
          url: "https://github.com/wangyida"
        - name: youtube
          url: "https://www.youtube.com/channel/UCvu4OW3TufWFsj-vNrzeEiw"
        - name: facebook
          url: "https://www.facebook.com/yida.wang.0123"
        - name: cv
          url: "https://wangyida.github.io/resume_yida_en.pdf"   

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: false # hide on single page

    editPost:
        URL: "https://github.com/<path_to_repo>/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: archive
          name: archive
          url: archives/
          weight: 5
        - identifier: categories
          name: categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20
        - identifier: labsite
          name: Lab-site
          url: http://campar.in.tum.de/Main/YidaWang
          weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

