baseURL: "https://wangyida.github.io/"
title: Yida Wang
paginate: 8
theme: hugo-PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Tags
          url: tags/
          weight: 10

  l2:
    languageName: "German"
    weight: 2
    title: Yida Wang
    profileMode:
      enabled: true
      title: Yida Wang
      imageUrl: "Photo_race.jpg"
      imageTitle: my image
      imageWidth: 120
      imageHeight: 120
      subtitle: "Ph.D. student focused on computer vision and machine learning"
      buttons:
        - name: Posts
          url: posts
        - name: Tags
          url: tags
    menu:
      main:
        - name: Archive
          url: archives/
          weight: 5
        - name: Tags
          url: tags
          weight: 10
        - name: Categories
          url: categories
          weight: 10
        - name: Series
          url: series
          weight: 10


  l3:
    languageName: "中文"
    languagedirection: rtl
    weight: 3
    title: 王一达
    homeInfoParams:
      Title: "王一达"
      Content: 中文页面正在更新，请参考中文简历
    menu:
      main:
        - name: Tags
          url: tags
          weight: 10

params:
  env: production
  description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
  author: Me
  # author: ["Me", "You"] # multiple authors
  ShowReadingTime: true
  defaultTheme: auto
  ShowShareButtons: true
  displayFullLangName: true
  images: "https://github.com/wangyida/website-hugo/blob/master/images/Photo_lab.jpg"
  cover:
    responsiveImages: false
    linkFullImages: false
  # assets:
  #   favicon: '<path / external url>'

  profileMode:
    enabled: false
    title: Yida Wang
    imageUrl: "https://github.com/wangyida/website-hugo/blob/master/images/Photo_lab.jpg"
    imageTitle: Yida Wang
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Yida Wang"
    Content: >
      I'm a Ph.D. student focused on computer vision and machine learning from [Technische Universität München](https://www.tum.de/), with topic of deep learning techniques for representation and processing of 3D data for complex visual tasks. Ever enrolled in competer vision projects sponsored by Microsoft and Google, *e.g.* [tiny-dnn](https://github.com/tiny-dnn/tiny-dnn) and [3D pose estimation](https://github.com/opencv/opencv_contrib/tree/master/modules/cnn_3dobj). [Presentation](/Presentation_Yida.pdf)

      > - **Download**: [My Resume](/resume_yida_en.pdf), [中文简历](/resume_yida_cn.pdf) and [Lebenslauf](/resume_yida_de.pdf)


  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/yida-wang-910123"
    - name: github
      url: "https://github.com/wangyida"
    - name: youtube
      url: "https://www.youtube.com/channel/UCvu4OW3TufWFsj-vNrzeEiw"
    - name: facebook
      url: "https://www.facebook.com/yida.wang.0123"

taxonomies:
  category: categories
  tag: tags
  series: series

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
